version: '3.8'
services:
    web:
      build: .
      ports:
        - "15000:5000"
      depends_on:
        - db
    db:
      image: postgres:15-alpine
      environment:
        - POSTGRES_USER=user
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=mydb